version: '3.8'

services:
  kani-tts-2:
    image: ghcr.io/ffrericks/kani-tts-2-docker:latest
    container_name: kani-tts-2
    ports:
      - "8001:8001"
    volumes:
      - /DATA/AppData/kani-tts-2/huggingface:/root/.cache/huggingface
      - /DATA/AppData/kani-tts-2/voices:/app/voices
    runtime: nvidia
    environment:
      - TZ=Europe/Amsterdam
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
    labels:
      - "casaos.ui.port=8001"
      - "casaos.ui.path=/"


x-casaos:
  architectures:
    - amd64
  main: kani-tts-2
  description:
    en_us: Fast, multilingual Text-to-Speech with voice cloning support, powered by Kani-TTS 2. Generates high-quality speech from text with GPU acceleration.
  tagline:
    en_us: AI Text-to-Speech 2 with Voice Cloning
  developer: nineninesix-ai
  author: ffrericks
  icon: https://raw.githubusercontent.com/ffrericks/kani-tts-2-docker/main/public/kani-TTS2-docker.png
  thumbnail: ""
  title:
    en_us: Kani TTS 2
  category: AI
  port_map: "8001"
  scheme: http
  index: /
